# numpy-Arrays

Die Datenstruktur, welche bei der Verwendung von Python für numerische Analysen bzw. Berechnungen verwendet wird, sind die numpy-Arrays. Im Gegensatz zu Listen, haben sie eine feste Länge und können n-dimensional sein. Der Vorteil der festen Längen und der Einschränkung auf einen festgelegten Datentyp ist die schnelle Verarbeitung und Speichereffizienz. Der Standarddatentyp sind 64-bit-Gleitkommazahlen.

In [1]:
import numpy as np
np.set_printoptions(precision=2, linewidth=65)

## Erzeugung

In [2]:
l1 = [5, 7, 3.4, -44.8, 34.1, 0, -0.04]
a1 = np.array(l1)
print("Liste:\n",l1)
print("Array:\n", a1)

Liste:
 [5, 7, 3.4, -44.8, 34.1, 0, -0.04]
Array:
 [ 5.00e+00  7.00e+00  3.40e+00 -4.48e+01  3.41e+01  0.00e+00
 -4.00e-02]


In [3]:
print( type(a1) )

<class 'numpy.ndarray'>


In [4]:
print( a1.dtype )

float64


In [5]:
N = 10
a2 = np.zeros(N)
a3 = np.zeros( (N, 3) )

print( a2 )
print( a3 )

print( a2.shape )
print( a3.shape )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(10,)
(10, 3)


In [6]:
a4 = np.arange(0, 3, 0.3)
print( a4 )

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


In [7]:
a5 = np.linspace(0, 3, N)
print( a5 )

[0.   0.33 0.67 1.   1.33 1.67 2.   2.33 2.67 3.  ]


## Zugriff

In [8]:
a6 = np.ones(10)
print( a6 )
a6[:6] = 2
print( a6 )
a6 = a6 + 5
print( a6 )
a6 = a6 * 2
print( a6 )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 1. 1. 1. 1.]
[7. 7. 7. 7. 7. 7. 6. 6. 6. 6.]
[14. 14. 14. 14. 14. 14. 12. 12. 12. 12.]


In [9]:
a7 = np.linspace(0, 3, len(a6))
print(a7)
a8 = a6 * a7
print(a8)

[0.   0.33 0.67 1.   1.33 1.67 2.   2.33 2.67 3.  ]
[ 0.    4.67  9.33 14.   18.67 23.33 24.   28.   32.   36.  ]


In [10]:
print(a8 > 20)

[False False False False False  True  True  True  True  True]


In [11]:
print( a8 )
a8[a8>20] = -1
print( a8 )

[ 0.    4.67  9.33 14.   18.67 23.33 24.   28.   32.   36.  ]
[ 0.    4.67  9.33 14.   18.67 -1.   -1.   -1.   -1.   -1.  ]


## Operationen

## Funktionen

In [12]:
x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)
print(x)
print(y)

[ 0.    0.13  0.25  0.38  0.51  0.63  0.76  0.89  1.02  1.14
  1.27  1.4   1.52  1.65  1.78  1.9   2.03  2.16  2.28  2.41
  2.54  2.67  2.79  2.92  3.05  3.17  3.3   3.43  3.55  3.68
  3.81  3.93  4.06  4.19  4.32  4.44  4.57  4.7   4.82  4.95
  5.08  5.2   5.33  5.46  5.59  5.71  5.84  5.97  6.09  6.22
  6.35  6.47  6.6   6.73  6.85  6.98  7.11  7.24  7.36  7.49
  7.62  7.74  7.87  8.    8.12  8.25  8.38  8.5   8.63  8.76
  8.89  9.01  9.14  9.27  9.39  9.52  9.65  9.77  9.9  10.03
 10.15 10.28 10.41 10.54 10.66 10.79 10.92 11.04 11.17 11.3
 11.42 11.55 11.68 11.8  11.93 12.06 12.19 12.31 12.44 12.57]
[ 0.00e+00  1.27e-01  2.51e-01  3.72e-01  4.86e-01  5.93e-01
  6.90e-01  7.76e-01  8.50e-01  9.10e-01  9.55e-01  9.85e-01
  9.99e-01  9.97e-01  9.79e-01  9.45e-01  8.96e-01  8.33e-01
  7.56e-01  6.67e-01  5.67e-01  4.58e-01  3.42e-01  2.20e-01
  9.51e-02 -3.17e-02 -1.58e-01 -2.82e-01 -4.01e-01 -5.14e-01
 -6.18e-01 -7.13e-01 -7.96e-01 -8.66e-01 -9.22e-01 -9.64e-01
 -9.90e-01 -1.00e+00 -9.