# numpy-Arrays

Die Datenstruktur, welche bei der Verwendung von Python für numerische Analysen bzw. Berechnungen verwendet wird, sind die numpy-Arrays. Im Gegensatz zu Listen, haben sie eine feste Länge und können n-dimensional sein. Der Vorteil der festen Längen und der Einschränkung auf einen festgelegten Datentyp ist die schnelle Verarbeitung und Speichereffizienz. Der Standarddatentyp sind 64-bit-Gleitkommazahlen.

In [1]:
import numpy as np
np.set_printoptions(precision=2, linewidth=65)

## Erzeugung

In [11]:
l1 = [5, 7, 3.4, -44.8, 34.1, 0, -0.04]
a1 = np.array(l1)
print("Liste:\n",l1)
print("Array:\n", a1)

Liste:
 [5, 7, 3.4, -44.8, 34.1, 0, -0.04]
Array:
 [ 5.00e+00  7.00e+00  3.40e+00 -4.48e+01  3.41e+01  0.00e+00
 -4.00e-02]


In [3]:
print( type(a1) )

<class 'numpy.ndarray'>


In [4]:
print( a1.dtype )

float64


In [5]:
N = 10
a2 = np.zeros(N)
a3 = np.zeros( (N, 3) )

print( a2 )
print( a3 )

print( a2.shape )
print( a3.shape )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(10,)
(10, 3)


In [6]:
a4 = np.arange(0, 3, 0.3)
print( a4 )

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7]


In [7]:
a5 = np.linspace(0, 3, N)
print( a5 )

[0.   0.33 0.67 1.   1.33 1.67 2.   2.33 2.67 3.  ]


## Zugriff

In [8]:
a6 = np.ones(10)
print( a6 )
a6[:6] = 2
print( a6 )
a6 = a6 + 5
print( a6 )
a6 = a6 * 2
print( a6 )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 1. 1. 1. 1.]
[7. 7. 7. 7. 7. 7. 6. 6. 6. 6.]
[14. 14. 14. 14. 14. 14. 12. 12. 12. 12.]


In [9]:
a7 = np.linspace(0, 3, len(a6))
print(a7)
a8 = a6 * a7
print(a8)

[0.   0.33 0.67 1.   1.33 1.67 2.   2.33 2.67 3.  ]
[ 0.    4.67  9.33 14.   18.67 23.33 24.   28.   32.   36.  ]


## Operationen