# Referenzen

Ein wichtiger Aspekt beim Arbieten mit Arrays – und auch mit Listen bzw. im Allgemeinen veränderbaren Datentypen – sind Referenzen. 

In [17]:
import numpy as np
np.set_printoptions(precision=2, linewidth=65)

## Motivation

Im folgenden Beispiel wird ein Teilbereich eines Arrays als Variable gespeichert.

In [66]:
original = np.arange(5, 15, 1.0)
bereich = original[3:8]

Mit den entsprechenden Formen:

In [67]:
print( original.shape )
print( bereich.shape )

(10,)
(5,)


Wird nun auf den Teilbereich zugegriffen, wird auch das Original verändert, da die Variable `bereich` nur eine Referenz, d.h. ein Zeiger oder Hinweis, auf eine andere Position ist.

In [70]:
print( original )
print( bereich )

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[ 8.  9. 10. 11. 12.]


In [71]:
bereich[:] = -12

In [72]:
print( original )
print( bereich )

[  5.   6.   7. -12. -12. -12. -12. -12.  13.  14.]
[-12. -12. -12. -12. -12.]


Es ist nicht möglich direkt abzulesen ob eine Variable als Referenz auf einen (Teil eines) Arrays verweist. Einig mit der Funktion `np.shares_memory` ist eine Überlappung des addressierten Speicherbereichs abfragbar. Ist diese Überlappung gegeben, so zeigen beide Variablen auf gleiche (Teil-) Bereiche. 

In [68]:
print( np.shares_memory(original, bereich) )

True


Und als Gegenprobe der Vergleich mit einem neu angelegten Array.

In [69]:
weiteres_array = np.arange(5, 15, 1.0)
print( np.shares_memory(weiteres_array, bereich) )

False


## Kopien

Soll auf dem Indexbereich gearbeitet werden und dabei die Werte verändert werden können ohne das Original zu ändern, muss eine Kopie erstellt werden. Dazu kann die `np.copy`-Funktion verwendet werden.

In [73]:
bereich = np.copy(original[3:8])
print( np.shares_memory(original, bereich) )

False


In [76]:
print( original )
print( bereich )

[  5.   6.   7. -12. -12. -12. -12. -12.  13.  14.]
[0. 0. 0. 0. 0.]


In [77]:
bereich[:] = 0

In [78]:
print( original )
print( bereich )

[  5.   6.   7. -12. -12. -12. -12. -12.  13.  14.]
[0. 0. 0. 0. 0.]


Der Vorteil von Referenzen ist, dass unnötige Kopien nicht gemacht werden müssen. Insbesondere bei großen Datenmengen wird so der Speicher- und Rechenbedarf deutlich reduziert.

## Funktionen

Auch beim Aufruf von Funktionen spielen Referenzen eine wichtige Rolle. Die folgende Funktion verdeutlicht dies.

In [3]:
# Funktion zum nullen von negativen Werten aus einer Liste
def entferne_negative(liste):
    ergebnis = liste
    for i in range(len(ergebnis)):
        if ergebnis[i] < 0:
            ergebnis[i] = 0
    return ergebnis

Gegeben sei eine Werteliste, welche auch negative Einträge hat. Die obige Funktion wird eine Liste zurückgeben, welche diese zu Null umgewandelt hat.

In [10]:
werte = [4, 8, -3, -1, 11, 2]
print( werte )

[4, 8, -3, -1, 11, 2]


Die Anwendung der Funktion auf die Werteliste und Ausgabe des Ergebnisses:

In [11]:
res = entferne_negative(werte)

print( res )

[4, 8, 0, 0, 11, 2]


Da aber in der Funktion implizit immer mit einer Referenz gearbeitet wurde, ist die originale Werteliste auch geändert.

In [12]:
print( werte )

[4, 8, 0, 0, 11, 2]


Ist dieses Verhalten nicht gewünscht, so kann auch in diesem Fall eine explizite Kopie zum Erhalt der übergebenen Werte führen. Hierzu stellt das copy-Modul eine entsprechende Funktion zum Kopieren von z.B. Listen bereit. 

In [14]:
import copy

# Obige Funktion mit Kopie
def entferne_negative_copy(liste):
    ergebnis = copy.copy(liste)
    for i in range(len(ergebnis)):
        if ergebnis[i] < 0:
            ergebnis[i] = 0
    return ergebnis

In [16]:
werte = [4, 8, -3, -1, 11, 2]
res = entferne_negative_copy(werte)
print( res )
print( werte )

[4, 8, 0, 0, 11, 2]
[4, 8, -3, -1, 11, 2]
