# Mehrdimensionale Daten

Die von Modul numpy bereitgestellten Array können mehrdimensional sein. Beispielsweise können so mehrere eindimensionale Datensätze in einer Datenstruktur gespeichert werden oder es handelt sich um mehrdimensionale Daten.

In [1]:
import numpy as np
np.set_printoptions(precision=2, linewidth=65)

## Zugriff

Dabei erfolg der Zugriff auf die Daten entsprechend nicht mehr über einen einzelnen Index, sondern über mehrere, welche mit einem Komma `,` getrennt werden.

In [2]:
N = 10
daten = np.zeros((10, 3))
print( daten )

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Genauso wie bei den verschachtelten Listen, gibt der erste Index die Unterstruktur, hier die Arrays mit drei Elementen, an. Der Zweite entsprechend den Index innerhalb des kurzen Arrays.

In [3]:
daten[0,2] = 5
print( daten )

[[0. 0. 5.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
daten[1,:] = 2
print( daten )

[[0. 0. 5.]
 [2. 2. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
daten[:, 1] = -1
print( daten )

[[ 0. -1.  5.]
 [ 2. -1.  2.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]
 [ 0. -1.  0.]]


## Einlesen